### PR TITLE
test: check limit().evaluate()

### PR DESCRIPTION
**Pull request by alexander-mart**
Test for https://github.com/terminusdb/terminusdb-client-js/issues/317

### CODE REVIEW

**Comment by hoijnet** [comment]
I added an integration test for this case in this PR:
https://github.com/terminusdb/terminusdb-client-js/pull/316

It works as of now and I could not reproduce. The arithmetic happens on the server side so need to do the query. Please modify the integration tests to trigger the error as it would help fix the issue.

It seems there is some kind of corner case that triggers your issue, but I can't understand why or reproduce at the moment. With the integration test in place, it should be easier to boil it down hopefully.

The integration test for it is called "Test simple arithmetic with vars variable handling", there is an equivalent with the string variable handling.

Thanks for your efforts, let's squash it!

**Comment by hoijnet** [comment]
The test you provided is not evaluated by the server and should thus look like this. Happy to pull in the test to ensure correct WOQL evaluation. This is the same WOQL as in the integration test.

```
  it('check limit().eval()', () => {
    let v = Vars("result");
    const woqlObject = WOQL.limit(100).eval(WOQL.times(2, 3), v.result);
    const expectedJson = {"@type":"Limit","limit":100,"query":{"@type":"Eval","expression":{"@type":"Times","left":{"@type":"ArithmeticValue","data":{"@type":"xsd:decimal","@value":2}},"right":{"@type":"ArithmeticValue","data":{"@type":"xsd:decimal","@value":3}}},"result":{"@type":"ArithmeticValue","variable":"result"}}};
    expect(woqlObject.json()).to.deep.eql(expectedJson);
  });
```

Let's try to find a reproducible case for how the incorrect WOQL with Value is generated.

**Comment by alexander-mart** [comment]
@hoijnet Test failing without any server (if I'm not mistaken), only with https://github.com/terminusdb/terminusdb-client-js/pull/315/files

```sh
  149 passing (177ms)
  1 failing

  1) woql queries
       check limit().evaluate():
     TypeError: WOQL.limit(...).evaluate is not a function
      at Context.<anonymous> (test/woql.spec.js:503:40)
      at processImmediate (node:internal/timers:478:21)
```

**Comment by hoijnet** [comment]
> @hoijnet I moved my answer to (original) issue, because there is full description a bug, but PR is only add test.
> 
> 
> 
> https://github.com/terminusdb/terminusdb/issues/2155#issuecomment-2827388728

The issue is that the test is incorrect, as it is never executed; it needs to be queries from the server to get a correct response. Please look at the test added in #316 for reference. Does it make sense to you too?

**Comment by alexander-mart** [comment]
@hoijnet What do you mean "it is never executed"? :thinking:

The test is definitely executed and fails with an error that the corresponding evaluate() method on the limit object was not found (same error from dashboard):

`TypeError: WOQL.limit(...).evaluate is not a function`

Or I don't understand correctly

---

>  it needs to be queries from the server to get a correct response

How do all the other similar tests in this file work then?

**Comment by hoijnet** [comment]
Please review against the latest head of the client, an integration test has been created for this now.

I think this PR should be closed. Please reopen and comment if you see things differently?
